name: 02- Workflow Events
on: 
  workflow_dispatch:

jobs:
  show-the-trigger:
    name: show-the-trigger
    runs-on: ubuntu-latest

    steps:
      - name: show the trigger
        run: |
          echo "This event was triggerred by $GITHUB_EVENT_NAME"
          echo "This event was triggerred by ${{ github.event_name }}"

