name: 03 - Workflow Runners
on:
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest

    steps:
      - name: ubuntu-echo
        run: |
          echo "This job is running on an below OS runner."
          echo "$RUNNER_OS"
          echo "${{ runner.os }}"

  mach-echo:
    runs-on: macos-latest

    steps:
      - name: mac-echo
        run: |
          echo "This job is running on an below OS runner."
          echo "$RUNNER_OS"
          echo "${{ runner.os }}"

  windows-echo:
    runs-on: windows-latest

    steps:
      - name: windows-echo
        shell: bash
        run: |
          echo "This job is running on an below OS runner."
          echo "$RUNNER_OS"
          echo "${{ runner.os }}"
