name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
  
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: debug Print start-up data
        if: inputs.debug == true
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github. }}"
          echo "Commit SHA: <retrieve the commit sha here>"
          echo "Runner OS: <retrieve the runner os here>"

