name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
  
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: '[debug] Print start-up data'
        if: inputs.debug
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: '[debug] Print when triggered from master'
        if: inputs.debug && github.ref == 'ref/heads/master'
        run: |
          echo "I was triggered from master"
      
      - name: Default Step
        run: |
          echo "I run whatever the condition maybe"
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
